openapi: 3.0.3
info:
  title: Class 2 Maternity Allowance Receipts
  description: |-
    # Usage Terms
    These interfaces are business-critical interfaces for HMRC and DWP, supporting thousands of staff - all consumption, or change in consumption levels, should be registered and fully approved (see Registered Consumers below).
  version: 0.0.4 Draft
  x-integration-catalogue:
    reviewed-date: 2026-01-13T16:47:25Z
    short-description: Class 2 Maternity Allowance Receipts
    status: ALPHA
    api-type: SIMPLE
    platform: HIP
    backends:
      - NI
    domain: 1
    sub-domain: 1.5
servers:
  - url: https://api.ipaas.prod.eis.ns2p.corp.hmrc.gov.uk/ni
    description: Corporate - Production
  - url: https://api.ipaas.preprod.eis.ns2p.corp.hmrc.gov.uk/ni
    description: Corporate – Pre-Production
  - url: https://api.ipaas.test.eis.ns2n.corp.hmrc.gov.uk/ni
    description: Corporate - Test
  - url: https://hip.ws.hmrc.gov.uk/ni
    description: MDTP - Production
  - url: https://hip.ws.ibt.hmrc.gov.uk/ni
    description: MDTP - QA
security:
  - oAuth2:
      - read:class-2-ma-receipts
paths:
  /class-2/{nino}/maternity-allowance/receipts:
    get:
      tags: []
      summary: Retrieve Class 2 Maternity Allowance Receipts
      description: |-
        # Purpose
        This API provides the capability to retrieve class 2 Maternity Allowance Receipts.<br>
        ## Version Log
        | Version | Date | Author | Description |
        |---------|------|--------|-------------|
        | 0.0.1 | 04/12/2025 | NPS Development Team  | Initial Draft  |
        | 0.0.2 | 13/01/2026 | NPS Development Team  | Added examples |
        | 0.0.3 | 20/02/2026 | NPS Development Team  | changed latest query to archived + added callbackURL + changed to nino + removing receivablePeriodEndDate & receivablePeriodStartDate|
        | 0.0.4 | 18/03/2026 | NPS Development Team  | Changed minimum payload|
      operationId: getClass2MAReceipts
      parameters:
        - $ref: '#/components/parameters/correlationId'
        - $ref: '#/components/parameters/govUkOriginatorId'
        - $ref: '#/components/parameters/govUkOrganisationId'
        - $ref: '#/components/parameters/govUkUserId'
        - $ref: '#/components/parameters/govUkUserName'
        - $ref: '#/components/parameters/govUkJobRole'
        - $ref: '#/components/parameters/FullNationalInsuranceNumber'
        - $ref: '#/components/parameters/Archived'
        - $ref: '#/components/parameters/ReceiptDate'
        - $ref: '#/components/parameters/SortBy'
      responses:
        "200":
          description: Successful Response
          headers:
            correlationId:
              $ref: '#/components/headers/correlationId'
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/GetClass2MAReceiptsResponse'
              examples:
                minimallyPopulatedResponse:
                  summary: Minimally populated response. No Class 2 MA receipts recorded.
                  value: {}
                exampleSingleOpenReceipt:
                  summary: One open receipt
                  value:
                    nationalInsuranceNumber: AA000002A
                    class2MAReceiptDetails:
                      - initials: AB
                        surname: Johnson
                        receivablePayment: 145.0
                        receiptDate: 2025-03-31
                        liabilityStart: 2025-01-01
                        liabilityEnd: 2025-03-31
                        billAmount: 145.0
                        billScheduleNumber: 1001
                        isClosedRecord: false
                        weeksPaid: 13
                maximallyPopulatedResponse:
                  summary: Maximally populated response
                  value:
                    nationalInsuranceNumber: AA000001A
                    class2MAReceiptDetails:
                      - initials: CD
                        surname: Smith
                        receivablePayment: 156.0
                        receiptDate: 2024-07-05
                        liabilityStart: 2024-04-06
                        liabilityEnd: 2024-07-05
                        billAmount: 156.0
                        billScheduleNumber: 2002
                        isClosedRecord: true
                        weeksPaid: 13
                      - initials: CD
                        surname: Smith
                        receivablePayment: 156.0
                        receiptDate: 2023-07-05
                        liabilityStart: 2023-04-06
                        liabilityEnd: 2023-07-05
                        billAmount: 156.0
                        billScheduleNumber: 2003
                        isClosedRecord: true
                        weeksPaid: 13
                    callback:
                      callbackURL: /class-2/AA000001/maternity-allowance/receipts?receiptDate=2023-06-27
        "400":
          description: Bad Request
          headers:
            correlationId:
              $ref: '#/components/headers/correlationId'
          content:
            application/json;charset=UTF-8:
              schema:
                required:
                  - origin
                  - response
                type: object
                properties:
                  origin:
                    $ref: '#/components/schemas/HIP-originEnum'
                  response:
                    oneOf:
                      - $ref: '#/components/schemas/HIP-failureResponse'
                      - $ref: '#/components/schemas/errorResponse_400'
                additionalProperties: false
              examples:
                Actual_Response:
                  value:
                    origin: HoD
                    response:
                      failures:
                        - reason: HTTP message not readable
                          code: "400.2"
                        - reason: "Constraint violation: Invalid/Missing input parameter:\
                          \ <parameter>"
                          code: "400.1"
                HIP-originResponse:
                  description: HIP-originResponse
                  value:
                    origin: HIP
                    response:
                      - type: Type of Failure
                        reason: Reason for Failure
        "403":
          description: 'Forbidden '
          headers:
            correlationId:
              $ref: '#/components/headers/correlationId'
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/errorResponse_403'
              examples:
                UserNotAuthorised_Response:
                  value:
                    reason: User Not Authorised
                    code: "403.1"
                Forbidden_Response:
                  value:
                    reason: Forbidden
                    code: "403.2"
        "404":
          $ref: '#/components/responses/notFoundErrorResponse'
        "500":
          $ref: '#/components/responses/internalServerErrorResponse'
        "422":
          description: Unprocessable Entity
          headers:
            correlationId:
              $ref: '#/components/headers/correlationId'
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/errorResponse_422'
        "503":
          description: Service Unavailable
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/HIP-originResponse'
components:
  schemas:
    EnumSortMAReceiptBy:
      enum:
        - DATE-OF-FINAL-PAYMENT-DESCENDING
        - DATE-OF-FINAL-PAYMENT-ASCENDING
      type: string
    correlationId:
      format: uuid
      description: Correlation ID - used for traceability purposes - note that this
        value in the response matches that received in the request to allow correlation.
      type: string
      example: e470d658-99f7-4292-a4a1-ed12c72f1337
    govUkOriginatorId:
      description: Identity of the Originating System that made the API call
      maxLength: 40
      minLength: 3
      type: string
    govUkOrganisationId:
      description: A unique organisation ID for the user.
      maxLength: 40
      minLength: 4
      type: string
      example: Department
    govUkUserId:
      description: A unique user ID for the user.
      maxLength: 7
      minLength: 7
      type: string
    govUkUserName:
      description: A unique username for the user.
      maxLength: 20
      minLength: 4
      type: string
      example: Worker
    govUkJobRole:
      description: A unique job role for the user.
      minLength: 4
      type: string
      example: Social
    nationalInsuranceNumberAndSuffix:
      description: National Insurance Number - unique for an individual - note not
        all individuals qualify to be issued with one.
      maxLength: 9
      minLength: 8
      pattern: "^((?:[ACEHJLMOPRSWXY][A-CEGHJ-NPR-TW-Z]|B[A-CEHJ-NPR-TW-Z]|G[ACEGHJ-NPR-TW-Z]|[KT][A-CEGHJ-MPR-TW-Z]|N[A-CEGHJL-NPR-SW-Z]|Z[A-CEGHJ-NPR-TW-Y])[0-9]{6}[A-D]?)$"
      type: string
      example: AA000001A
    receivablePayment:
      description: The receivable payment of the receipt.
      multipleOf: 0.01
      maximum: 99999999999999.98
      minimum: -99999999999999.98
      type: number
      example: 10.56
    receiptDate:
      format: date
      description: The date that the receipt was published.
      type: string
      example: 2023-06-27
    liabilityStart:
      format: date
      description: The date on which this liability started.
      type: string
      example: 2023-06-27
    liabilityEnd:
      format: date
      description: The date on which this liability ended.
      type: string
      example: 2023-06-27
    billAmount:
      description: Bill amount of the class 2 MA receipt
      multipleOf: 0.01
      maximum: 99999999999999.98
      minimum: -99999999999999.98
      type: number
      example: 10.56
    billScheduleNumber:
      description: Bill schedule number of the class 2 MA receipt
      type: integer
    isClosedRecord:
      description: Confirms if the receipt is a closed / paid receipt.
      type: boolean
    weeksPaid:
      description: A calculated number of weeks paid
      type: integer
    initials:
      description: The Initials of the customer.
      maxLength: 2
      minLength: 1
      pattern: "^([A-Za-z '-])+$"
      type: string
      example: JP
    surname:
      description: The surname of the individual.
      maxLength: 99
      minLength: 2
      pattern: "^([A-Za-z '-])+$"
      type: string
      example: van Cholmondley-warner
    errorResponse_400:
      title: Error Response
      description: Array of Error Response Failure Object in Error Response.
      type: object
      properties:
        failures:
          type: array
          items:
            $ref: '#/components/schemas/errorResourceObj_400'
    errorResourceObj_400:
      required:
        - code
        - reason
      type: object
      properties:
        reason:
          description: Displays the reason of the failure.
          maxLength: 128
          minLength: 1
          type: string
        code:
          description: |-
            The error code representing the error that has occurred. Valid values are
            400.1 - Constraint violation (Followed by 'Invalid/Missing input parameter path.to.field'
            400.2 - HTTP message not readable;
          enum:
            - "400.1"
            - "400.2"
          type: string
    errorResponse_403:
      title: Forbidden Error Response
      description: Error Response Payload for this API
      oneOf:
        - $ref: '#/components/schemas/errorResourceObj_403_Forbidden'
        - $ref: '#/components/schemas/errorResourceObj_403_UserNotAuthorised'
    errorResourceObj_403_Forbidden:
      title: 403_Forbidden
      required:
        - code
        - reason
      type: object
      properties:
        reason:
          description: Displays the reason of the failure.
          enum:
            - Forbidden
          type: string
        code:
          description: The error code representing the Forbidden Error.
          enum:
            - "403.2"
          type: string
    errorResourceObj_403_UserNotAuthorised:
      title: 403_UserNotAuthorised
      required:
        - code
        - reason
      type: object
      properties:
        reason:
          description: Displays the reason of the failure.
          enum:
            - User Not Authorised
          type: string
        code:
          description: User Not Authorised.
          enum:
            - "403.1"
          type: string
    errorResponse_422:
      title: Error Response
      description: Error Response Payload for this API
      type: object
      properties:
        failures:
          $ref: '#/components/schemas/errorResponseFailure_422'
    errorResponseFailure_422:
      title: Failure Object in Error Response
      description: Array of Error Response Failure Object in Error Response.
      type: array
      items:
        $ref: '#/components/schemas/errorResourceObj_422'
    errorResourceObj_422:
      required:
        - code
        - reason
      type: object
      properties:
        reason:
          description: Displays the reason of the failure.
          maxLength: 128
          minLength: 1
          type: string
        code:
          description: The error code representing the error that has occurred.
          maxLength: 10
          minLength: 1
          type: string
    Class2MAReceiptDetails:
      description: Contains MA Receipt details associated with an individual.
      type: object
      properties:
        initials:
          $ref: '#/components/schemas/initials'
        surname:
          $ref: '#/components/schemas/surname'
        receivablePayment:
          $ref: '#/components/schemas/receivablePayment'
        receiptDate:
          $ref: '#/components/schemas/receiptDate'
        liabilityStart:
          $ref: '#/components/schemas/liabilityStart'
        liabilityEnd:
          $ref: '#/components/schemas/liabilityEnd'
        billAmount:
          $ref: '#/components/schemas/billAmount'
        billScheduleNumber:
          $ref: '#/components/schemas/billScheduleNumber'
        isClosedRecord:
          $ref: '#/components/schemas/isClosedRecord'
        weeksPaid:
          $ref: '#/components/schemas/weeksPaid'
    callback:
      properties:
        callbackURL:
          description: A URL in the response body that redirects the user to call
            the next set of data based on the prepared URL. This will only be populated
            if the call has not returned all the relevant data and another call is
            required.
          type: string
    GetClass2MAReceiptsResponse:
      description: Success response payload for this API.
      type: object
      properties:
        nationalInsuranceNumber:
          $ref: '#/components/schemas/nationalInsuranceNumberAndSuffix'
        class2MAReceiptDetails:
          description: Contains an array of Class 2 MA Receipt details.
          type: array
          items:
            $ref: '#/components/schemas/Class2MAReceiptDetails'
        callback:
          $ref: '#/components/schemas/callback'
    HIP-originEnum:
      enum:
        - HIP
        - HoD
      type: string
    HIP-failureResponse:
      required:
        - failures
      type: object
      properties:
        failures:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
              - type
              - reason
            type: object
            properties:
              type:
                type: string
              reason:
                type: string
            additionalProperties: false
    HIP-originResponse:
      required:
        - origin
        - response
      type: object
      properties:
        origin:
          $ref: '#/components/schemas/HIP-originEnum'
        response:
          $ref: '#/components/schemas/HIP-failureResponse'
      additionalProperties: false
  responses:
    notFoundErrorResponse:
      description: The requested resource could not be found
      headers:
        correlationId:
          $ref: '#/components/headers/correlationId'
    internalServerErrorResponse:
      description: Internal Server Error
      headers:
        correlationId:
          $ref: '#/components/headers/correlationId'
  parameters:
    correlationId:
      name: correlationId
      in: header
      description: Correlation ID - used for traceability purposes - note that this
        value in the response matches that received in the request to allow correlation.
      required: true
      schema:
        $ref: '#/components/schemas/correlationId'
    govUkOriginatorId:
      name: gov-uk-originator-id
      in: header
      description: Identity of the Originating System that made the API call.
      required: true
      schema:
        $ref: '#/components/schemas/govUkOriginatorId'
    govUkOrganisationId:
      name: gov-uk-organisation-id
      in: header
      description: A unique organisation ID for the user.
      schema:
        $ref: '#/components/schemas/govUkOrganisationId'
    govUkUserId:
      name: gov-uk-user-id
      in: header
      description: A unique user ID for the user.
      required: false
      schema:
        $ref: '#/components/schemas/govUkUserId'
    govUkUserName:
      name: gov-uk-user-name
      in: header
      description: A unique username for the user.
      schema:
        $ref: '#/components/schemas/govUkUserName'
    govUkJobRole:
      name: gov-uk-job-role
      in: header
      description: A unique job role for the user.
      schema:
        $ref: '#/components/schemas/govUkJobRole'
    FullNationalInsuranceNumber:
      name: nino
      in: path
      description: National Insurance Number - unique for an individual - note not
        all individuals qualify to be issued with one.
      required: true
      schema:
        $ref: '#/components/schemas/nationalInsuranceNumberAndSuffix'
    Archived:
      name: archived
      in: query
      description: "Flag to determine if the consuming system wants to access archived/\
        \ active class 2 MA receipts. Active records are those not closed/paid by\
        \ the customer. Default behaviour is Archived = false, returning active/open\
        \ records."
      required: false
      schema:
        type: boolean
      example: true
    ReceiptDate:
      name: receiptDate
      in: query
      description: Filter by Receipt Date - this is a restart key. This should only
        be populated if the previous call did not transfer all of the data i.e. there
        are more rows marked to be collected still.
      required: false
      schema:
        $ref: '#/components/schemas/receiptDate'
    SortBy:
      name: type
      in: query
      description: Capabilities of data sort.
      required: false
      schema:
        $ref: '#/components/schemas/EnumSortMAReceiptBy'
  headers:
    correlationId:
      required: true
      schema:
        $ref: '#/components/schemas/correlationId'
  securitySchemes:
    oAuth2:
      type: oauth2
      description: OAuth2 Client Credentials Flow
      flows:
        clientCredentials:
          tokenUrl: /tokenUrl/not-required
          scopes:
            read:class-2-ma-receipts: Class 2 MA Receipts
